### ISSUE TITLE
Duplicated reports for "javascript"

### ISSUE THREAD

**Issue by io-monad** [azu/technical-word-rules#14]
Hi,

I've just found `spellCheckText` on the word `"javascript"` emits the same message twice.

``` js
> require("spellcheck-technical-word").spellCheckText("javascript")
[ { actual: 'javascript',
    expected: 'JavaScript',
    paddingIndex: 0,
    paddingLine: 0,
    paddingColumn: 0 },
  { actual: 'javascript',
    expected: 'JavaScript',
    paddingIndex: 0,
    paddingLine: 0,
    paddingColumn: 0 } ]
```

(Tested by `spellcheck-technical-word@2.0.0`)

So `textlint-rule-spellcheck-tech-word` has the same issue as this.

**Comment by io-monad** [comment]
Wow, thanks for quick fix!

**Comment by azu** [comment]
This repository apply [semantic-release](https://github.com/semantic-release/semantic-release).
Automatically publish to npm :soon:
