### ISSUE TITLE
publish のお願い

### ISSUE THREAD

**Issue by januswel** [azu/technical-word-rules#20]
これを反映させるために publish をお願いしたいです。

https://github.com/azu/technical-word-rules/commit/6ba112e99bb140fbfb49f25cce5bcec92845d501

publish 前に何か作業が必要であればお手伝いできると思いますので、言ってください。

**Comment by azu** [comment]
semantic-releaseを使っていたのですが、[この問題の影響](https://blog.npmjs.org/post/175824896885/incident-report-npm-inc-operations-incident-of)でtokenがrevokeされていたので動かなくなっていたようでした。
手動でpublishしてみました。

最近、別の仕組みに移っていたのでこの辞書はあまり使わなくなっていました。(イマイチ完成度が中途半端なのですが)
https://proofdict.github.io/
https://github.com/azu/proof-dictionary/

**Comment by januswel** [comment]
ありがとうございます
ご面倒かけてすみません

- https://proofdict.github.io/
- https://github.com/azu/proof-dictionary/

fork して自分の辞書を育てていくのですね
非常に面白い試みだと思います
今後こちらいじってみますね

**Comment by januswel** [comment]
1.9.5 確認しました
が、 `regexpMustEmpty` が all.json に含まれていないからなのか、意図通りに動作しません

proof-dictionary を試してみます
